import { describe, test, expect } from "bun:test";
import { z } from "zod";
import { generateEnvExample } from "../src/generate.js";
import { sensitive } from "../src/sensitive.js";

describe("generateEnvExample", () => {
  test("generates example for simple schema", () => {
    const output = generateEnvExample({
      PORT: z.coerce.number().default(3000),
      HOST: z.string().default("localhost"),
    });

    expect(output).toContain("PORT=3000");
    expect(output).toContain("HOST=localhost");
    expect(output).toContain("optional");
  });

  test("marks required vars", () => {
    const output = generateEnvExample({
      DATABASE_URL: z.string().url(),
    });

    expect(output).toContain("DATABASE_URL=");
    expect(output).toContain("required");
  });

  test("includes descriptions", () => {
    const output = generateEnvExample({
      DATABASE_URL: z.string().url().describe("PostgreSQL connection string"),
    });

    expect(output).toContain("PostgreSQL connection string");
  });

  test("marks sensitive keys", () => {
    const output = generateEnvExample(
      {
        API_SECRET: z.string(),
      },
      ["API_SECRET"]
    );

    expect(output).toContain("sensitive");
  });

  test("marks sensitive via helper", () => {
    const output = generateEnvExample({
      TOKEN: sensitive(z.string()),
    });

    expect(output).toContain("sensitive");
  });

  test("shows enum values", () => {
    const output = generateEnvExample({
      NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
    });

    expect(output).toContain("development | production | test");
  });

  test("includes header comments", () => {
    const output = generateEnvExample({ FOO: z.string() });
    expect(output).toContain("Generated by envprotect");
  });
});
