import {
  type ZodType,
  type ZodDefault,
  type ZodOptional,
  type ZodEnum,
  ZodString,
  ZodNumber,
  ZodBoolean,
} from "zod";
import type { SensitiveSchema, EnvSchema } from "./createEnv.js";

interface FieldInfo {
  key: string;
  required: boolean;
  defaultValue?: string;
  description?: string;
  type: string;
  sensitive: boolean;
}

function getZodTypeInfo(schema: ZodType<any>): { type: string; innerDef: any } {
  const def = (schema as any)._def;

  if (def.typeName === "ZodDefault") {
    const inner = getZodTypeInfo(def.innerType);
    return { ...inner };
  }
  if (def.typeName === "ZodOptional") {
    const inner = getZodTypeInfo(def.innerType);
    return { ...inner };
  }
  if (def.typeName === "ZodEffects") {
    // z.coerce.*
    const inner = getZodTypeInfo(def.schema);
    return { ...inner };
  }
  if (def.typeName === "ZodString") return { type: "string", innerDef: def };
  if (def.typeName === "ZodNumber") return { type: "number", innerDef: def };
  if (def.typeName === "ZodBoolean") return { type: "boolean", innerDef: def };
  if (def.typeName === "ZodEnum") return { type: def.values.join(" | "), innerDef: def };
  return { type: "string", innerDef: def };
}

function isOptional(schema: ZodType<any>): boolean {
  const def = (schema as any)._def;
  if (def.typeName === "ZodOptional") return true;
  if (def.typeName === "ZodDefault") return true;
  if (def.typeName === "ZodEffects") return isOptional(def.schema);
  return false;
}

function getDefault(schema: ZodType<any>): string | undefined {
  const def = (schema as any)._def;
  if (def.typeName === "ZodDefault") {
    const val = def.defaultValue();
    return val !== undefined ? String(val) : undefined;
  }
  if (def.typeName === "ZodOptional") return getDefault(def.innerType);
  if (def.typeName === "ZodEffects") return getDefault(def.schema);
  return undefined;
}

function getDescription(schema: ZodType<any>): string | undefined {
  if (schema.description) return schema.description;
  const def = (schema as any)._def;
  if (def.typeName === "ZodDefault") return getDescription(def.innerType);
  if (def.typeName === "ZodOptional") return getDescription(def.innerType);
  if (def.typeName === "ZodEffects") return getDescription(def.schema);
  return undefined;
}

/**
 * Generate .env.example content from a schema.
 */
export function generateEnvExample(
  schema: EnvSchema,
  sensitiveKeys: string[] = []
): string {
  const sensitiveSet = new Set(sensitiveKeys);
  const lines: string[] = [
    "# Environment Variables",
    "# Generated by envprotect",
    "#",
    "",
  ];

  for (const [key, zodSchema] of Object.entries(schema)) {
    const optional = isOptional(zodSchema);
    const defaultVal = getDefault(zodSchema);
    const description = getDescription(zodSchema);
    const { type } = getZodTypeInfo(zodSchema);
    const isSensitive =
      sensitiveSet.has(key) || (zodSchema as SensitiveSchema)._sensitive;

    const parts: string[] = [];
    parts.push(optional ? "(optional" : "(required");
    if (defaultVal !== undefined) parts[parts.length - 1] += `, default: ${defaultVal}`;
    parts[parts.length - 1] += ")";
    if (isSensitive) parts.push("sensitive");
    parts.push(type);
    if (description) parts.push(description);

    const comment = parts.join(" ");
    const value = defaultVal ?? "";

    lines.push(`# ${comment}`);
    lines.push(`${key}=${value}`);
    lines.push("");
  }

  return lines.join("\n");
}
